/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaVisao;

import com.nohair.controle.IMotoristaControle;
import com.nohair.controle.MotoristaControle;
import com.nohair.modelos.Motorista;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class TelaAdminBuscarMotorista extends javax.swing.JFrame {

    IMotoristaControle imc = new MotoristaControle();
    IMotoristaControle MotoristaControle = new MotoristaControle();
    
    /**
     * Creates new form TelaAdminBuscarMotorista
     */
    public TelaAdminBuscarMotorista() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            //imprimirDadosNaGrid(MotoristaControle.buscarMotorista());
            imprimirDadosNaGrid(imc.listagem());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1TabelaMotoraBuscar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1NomeBuscarMotora = new javax.swing.JTextField();
        jLabel3TelefoneMotorista = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6EnderecoMotorista = new javax.swing.JLabel();
        jLabel4CNHmotorista = new javax.swing.JLabel();
        jLabel5VencimentoCNHmotorista = new javax.swing.JLabel();
        jLabel5VencimentoCNHmotorista1 = new javax.swing.JLabel();
        jTextField2AlterarNomeMotora = new javax.swing.JTextField();
        jTextField3AlterarTelefoneMotora = new javax.swing.JTextField();
        jTextField4AlterarEnderecoMotora = new javax.swing.JTextField();
        jTextField5AlterarCNHmotora = new javax.swing.JTextField();
        jTextField6AlterarNumeroCNHMotora = new javax.swing.JTextField();
        jTextField7AlterarURLMotora = new javax.swing.JTextField();
        jLabel3FotoCNH = new javax.swing.JLabel();
        jButton1BuscarFoto = new javax.swing.JButton();
        jButton2BuscarMotora = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3Voltar = new javax.swing.JButton();
        jButton4SalvarAlteracao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2AlterarIDMotora = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(670, 750));

        jTable1TabelaMotoraBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone", "Endereço", "Numero CNH", "Venc CNH", "URL"
            }
        ));
        jTable1TabelaMotoraBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1TabelaMotoraBuscarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1TabelaMotoraBuscar);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome ");

        jLabel3TelefoneMotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3TelefoneMotorista.setText("Telefone");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome ");

        jLabel6EnderecoMotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6EnderecoMotorista.setText("Endereço");

        jLabel4CNHmotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4CNHmotorista.setText("Nº CNH");

        jLabel5VencimentoCNHmotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5VencimentoCNHmotorista.setText("Venc. CNH");

        jLabel5VencimentoCNHmotorista1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5VencimentoCNHmotorista1.setText("Foto URL");

        jLabel3FotoCNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1BuscarFoto.setText("Buscar Foto");
        jButton1BuscarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarFotoActionPerformed(evt);
            }
        });

        jButton2BuscarMotora.setText("Buscar Motorista");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Alterar Motorista");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Buscar Motorista");

        jLabel6.setText("__________________________________________________________________________________________________________________");

        jButton3Voltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3Voltar.setText("Voltar");
        jButton3Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3VoltarActionPerformed(evt);
            }
        });

        jButton4SalvarAlteracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4SalvarAlteracao.setText("Alterar");
        jButton4SalvarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4SalvarAlteracaoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5VencimentoCNHmotorista1)
                                                    .addComponent(jLabel5VencimentoCNHmotorista))
                                                .addGap(45, 45, 45))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField6AlterarNumeroCNHMotora, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(93, 93, 93)
                                                .addComponent(jButton1BuscarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField3AlterarTelefoneMotora, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField1NomeBuscarMotora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(65, 65, 65)
                                                .addComponent(jButton2BuscarMotora, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField4AlterarEnderecoMotora, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField5AlterarCNHmotora, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(43, 43, 43)
                                                    .addComponent(jLabel3FotoCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jTextField7AlterarURLMotora, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3TelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField2AlterarNomeMotora, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4CNHmotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6EnderecoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2AlterarIDMotora, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton3Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4SalvarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1NomeBuscarMotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2BuscarMotora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2AlterarIDMotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2AlterarNomeMotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3TelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3AlterarTelefoneMotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6EnderecoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4AlterarEnderecoMotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4CNHmotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5AlterarCNHmotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3FotoCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5VencimentoCNHmotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6AlterarNumeroCNHMotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1BuscarFoto))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7AlterarURLMotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5VencimentoCNHmotorista1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4SalvarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1BuscarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarFotoActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fc = new JFileChooser();
            File logo = new File("./src/com/nohair/fotoMotorista");
            fc.setCurrentDirectory(logo);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            String nome = arquivo.getName();
            String url = logo.getPath();
            url += "/" + nome;
            System.out.println(url);
            jTextField7AlterarURLMotora.setText(url);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(jLabel3FotoCNH.getWidth(), jLabel3FotoCNH.getHeight(), 1));
            jLabel3FotoCNH.setIcon(iconLogo);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Selecione a foto do motorista");
        }
    }//GEN-LAST:event_jButton1BuscarFotoActionPerformed

    private void jTable1TabelaMotoraBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1TabelaMotoraBuscarMouseClicked
        // TODO add your handling code here:
        try {
            jTextField2AlterarIDMotora.setText(jTable1TabelaMotoraBuscar.getValueAt(jTable1TabelaMotoraBuscar.getSelectedRow(), 0).toString());
            jTextField2AlterarNomeMotora.setText(jTable1TabelaMotoraBuscar.getValueAt(jTable1TabelaMotoraBuscar.getSelectedRow(), 1).toString());
            jTextField3AlterarTelefoneMotora.setText(jTable1TabelaMotoraBuscar.getValueAt(jTable1TabelaMotoraBuscar.getSelectedRow(), 2).toString());
            jTextField4AlterarEnderecoMotora.setText(jTable1TabelaMotoraBuscar.getValueAt(jTable1TabelaMotoraBuscar.getSelectedRow(), 3).toString());
            jTextField5AlterarCNHmotora.setText(jTable1TabelaMotoraBuscar.getValueAt(jTable1TabelaMotoraBuscar.getSelectedRow(), 4).toString());
            jTextField6AlterarNumeroCNHMotora.setText(jTable1TabelaMotoraBuscar.getValueAt(jTable1TabelaMotoraBuscar.getSelectedRow(), 5).toString());
            String nomeArquivo = (String) this.jTable1TabelaMotoraBuscar.getValueAt(jTable1TabelaMotoraBuscar.getSelectedRow(), 6);
            jTextField7AlterarURLMotora.setText(nomeArquivo);
            ImageIcon iconLogo = new ImageIcon(nomeArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(jLabel3FotoCNH.getWidth(), jLabel3FotoCNH.getHeight(), 1));
            jLabel3FotoCNH.setIcon(iconLogo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jTable1TabelaMotoraBuscarMouseClicked

    private void jButton4SalvarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4SalvarAlteracaoActionPerformed
        // TODO add your handling code here:
        try {

            //IMotoristaControle incluirMotorista = new MotoristaControle();
            Motorista objeto = new Motorista(Integer.parseInt(jTextField2AlterarIDMotora.getText()), jTextField2AlterarNomeMotora.getText(), jTextField3AlterarTelefoneMotora.getText(),jTextField4AlterarEnderecoMotora.getText(),jTextField5AlterarCNHmotora.getText(),jTextField6AlterarNumeroCNHMotora.getText(), jTextField7AlterarURLMotora.getText());
            MotoristaControle.alterar(objeto);
            /*Motorista objetoMotorista = new Motorista();
            objetoMotorista.setFotoMotoristaURL(jTextField7AlterarURLMotora.getText());
            incluirMotorista.alterar(objeto);
            */
            imprimirDadosNaGrid(MotoristaControle.listagem());
        
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Não foi possivel fazer a alteração");

        }
        //jTextFieldDescricao.setText("");
    }//GEN-LAST:event_jButton4SalvarAlteracaoActionPerformed

    private void jButton3VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3VoltarActionPerformed
        // TODO add your handling code here:
        telaAdminOpcoes f = new telaAdminOpcoes();
            this.dispose();                     // Fechar a tela ao abrir outra janela
            f.setLocationRelativeTo(null);      // Comando para centralizar a aplicação no centro do monitor
            f.setVisible(true);
    }//GEN-LAST:event_jButton3VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdminBuscarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdminBuscarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdminBuscarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdminBuscarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdminBuscarMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1BuscarFoto;
    private javax.swing.JButton jButton2BuscarMotora;
    private javax.swing.JButton jButton3Voltar;
    private javax.swing.JButton jButton4SalvarAlteracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3FotoCNH;
    private javax.swing.JLabel jLabel3TelefoneMotorista;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4CNHmotorista;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5VencimentoCNHmotorista;
    private javax.swing.JLabel jLabel5VencimentoCNHmotorista1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6EnderecoMotorista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1TabelaMotoraBuscar;
    private javax.swing.JTextField jTextField1NomeBuscarMotora;
    private javax.swing.JTextField jTextField2AlterarIDMotora;
    private javax.swing.JTextField jTextField2AlterarNomeMotora;
    private javax.swing.JTextField jTextField3AlterarTelefoneMotora;
    private javax.swing.JTextField jTextField4AlterarEnderecoMotora;
    private javax.swing.JTextField jTextField5AlterarCNHmotora;
    private javax.swing.JTextField jTextField6AlterarNumeroCNHMotora;
    private javax.swing.JTextField jTextField7AlterarURLMotora;
    // End of variables declaration//GEN-END:variables

    private void imprimirDadosNaGrid(ArrayList<Motorista> listaDeMotorista){
        try {
            DefaultTableModel model =  (DefaultTableModel) jTable1TabelaMotoraBuscar.getModel();
            //Limpa a tabela 
            model.setNumRows(0);
            
            Iterator<Motorista> lista = listaDeMotorista.iterator();
            
            while(lista.hasNext()){
                
                String[] saida= new String[7];
                
                Motorista aux = lista.next();
                saida[0]= aux.getId()+"";
                saida[1]= aux.getNome();
                saida[2] = aux.getTelefone();
                saida[3] = aux.getEndereco();//
                saida[4] = aux.getNumeroCNH();//
                saida[5] = aux.getDataVencimentoCNH();//
                saida[6] = aux.getFotoMotoristaURL();
                
                
                model.addRow(saida);
                
            } } 
        catch(Exception erro){
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }  
}
}
