/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package telaVisao;

import com.nohair.controle.IMotoristaControle;
import com.nohair.controle.MotoristaControle;
import com.nohair.modelos.Motorista;
import com.nohair.persistencia.MotoristaDao;
import java.io.File;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;

import javax.swing.text.MaskFormatter;

/**
 *
 * @author bruno
 */
public class TelaAdminCadMotorista extends javax.swing.JFrame {
    IMotoristaControle MotoristaControle = new MotoristaControle();
    
    //Mascaras Motorista ...
    private MaskFormatter telefoneMask;
    private MaskFormatter numeroCNHMask;
    private MaskFormatter vencimentoMask;
    
    

    /** Creates new form TelaAdminCadMotorista */
    public TelaAdminCadMotorista() throws ParseException {
        initComponents();
        MotoristaDao objeto = new MotoristaDao();
        objeto.ChecarTxt();
        // Inicializa a Mascara CNPJ / CPF / ...
            telefoneMask = new MaskFormatter("(##)#####-####");
            numeroCNHMask = new MaskFormatter("#########-##");
            vencimentoMask = new MaskFormatter("##/##/####");
            
        this.setLocationRelativeTo(null);
         try {
             ArrayList<Motorista> lista = MotoristaControle.listagem();
             if(!lista.isEmpty()){
                //imprimirDadosNaGrid(adminControle.listagem());
             }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
            
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2NomeMotorista = new javax.swing.JLabel();
        jLabel3TelefoneMotorista = new javax.swing.JLabel();
        jLabel4CNHmotorista = new javax.swing.JLabel();
        jLabel5VencimentoCNHmotorista = new javax.swing.JLabel();
        jLabel6EnderecoMotorista = new javax.swing.JLabel();
        jTextField1NomeMotorista = new javax.swing.JTextField();
        jTextField1TelefoneMotorista = new javax.swing.JTextField();
        jTextField1EnderecoMotorista = new javax.swing.JTextField();
        jTextField1NumeroCNH = new javax.swing.JTextField();
        jTextField1VencimentoCNH = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1BuscarImagemCNH = new javax.swing.JButton();
        jLabel5VencimentoCNHmotorista1 = new javax.swing.JLabel();
        jTextField1FotoURL = new javax.swing.JTextField();
        jLabel2FotoCNH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Motorista");

        jLabel2NomeMotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2NomeMotorista.setText("Nome");

        jLabel3TelefoneMotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3TelefoneMotorista.setText("Telefone");

        jLabel4CNHmotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4CNHmotorista.setText("Nº CNH");

        jLabel5VencimentoCNHmotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5VencimentoCNHmotorista.setText("Vencimento CNH");

        jLabel6EnderecoMotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6EnderecoMotorista.setText("Endereço");

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1BuscarImagemCNH.setText("Buscar Imagem");
        jButton1BuscarImagemCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarImagemCNHActionPerformed(evt);
            }
        });

        jLabel5VencimentoCNHmotorista1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5VencimentoCNHmotorista1.setText("Foto URL");

        jLabel2FotoCNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(176, 176, 176))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6EnderecoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4CNHmotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3TelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2NomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(44, 44, 44))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5VencimentoCNHmotorista)
                                            .addGap(18, 18, 18)))
                                    .addComponent(jLabel5VencimentoCNHmotorista1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1FotoURL, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField1TelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField1NumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField1VencimentoCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField1EnderecoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField1NomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel2FotoCNH, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1BuscarImagemCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2FotoCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1TelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2NomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3TelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1NomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6EnderecoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1EnderecoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4CNHmotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1NumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1BuscarImagemCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5VencimentoCNHmotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1VencimentoCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5VencimentoCNHmotorista1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1FotoURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
           
            if(!jTextField1NomeMotorista.getText().equals("") && !jTextField1TelefoneMotorista.getText().equals("") && !jTextField1EnderecoMotorista.getText().equals("") && !jTextField1NumeroCNH.getText().equals("") && !jTextField1VencimentoCNH.getText().equals("")){
            
        
            Motorista objeto = new Motorista(0,jTextField1NomeMotorista.getText(),jTextField1TelefoneMotorista.getText(),jTextField1EnderecoMotorista.getText(),jTextField1NumeroCNH.getText(),jTextField1VencimentoCNH.getText(), jTextField1FotoURL.getText());
            MotoristaControle.incluir(objeto);
            jTextField1NomeMotorista.setText("");
            jTextField1TelefoneMotorista.setText("");
            jTextField1EnderecoMotorista.setText("");
            jTextField1NumeroCNH.setText("");
            jTextField1VencimentoCNH.setText("");
            jTextField1FotoURL.setText("");
            JOptionPane.showMessageDialog(this,"Motorista Cadastrado com sucesso");
            //imprimirDadosNaGrid(MotoristaControle.listagem());
            
              /*
                    jTextField1TelefoneMotorista.setFormatterFactory(new DefaultFormatterFactory(telefoneMask));
                    jTextField1TelefoneMotorista.setValue(null);
                    jTextField1NumeroCNH.setFormatterFactory(new DefaultFormatterFactory(numeroCNHMask));
                    jTextField1NumeroCNH.setValue(null);
                    jTextField1VencimentoCNH.setFormatterFactory(new DefaultFormatterFactory(vencimentoMask));
                    jTextField1VencimentoCNH.setValue(null);
                  */
            
            }                
            else{
                //Se houver campo vazio no cadastro e mostrado uma mensagem !
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar, confira se todos os dados foram inseridos corretamente ou contate o suporte pelo contato 62982971994");
            }    
            
          
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this,"Erro ao Cadastrar, contate o suporte pelo contato 62982971994");
           
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        telaAdminOpcoes f = new telaAdminOpcoes();
            this.dispose();                     // Fechar a tela ao abrir outra janela
            f.setLocationRelativeTo(null);      // Comando para centralizar a aplicação no centro do monitor
            f.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1BuscarImagemCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarImagemCNHActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fc = new JFileChooser();
            File logo = new File("./src/com/nohair/fotoMotorista");
            fc.setCurrentDirectory(logo);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            String nome = arquivo.getName();
            String url = logo.getPath();
            url += "/" + nome;
            System.out.println(url);
            jTextField1FotoURL.setText(url);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(jLabel2FotoCNH.getWidth(), jLabel2FotoCNH.getHeight(), 1));
            jLabel2FotoCNH.setIcon(iconLogo);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Selecione a foto do motorista");
        }
    }//GEN-LAST:event_jButton1BuscarImagemCNHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdminCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdminCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdminCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdminCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaAdminCadMotorista().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(TelaAdminCadMotorista.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1BuscarImagemCNH;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2FotoCNH;
    private javax.swing.JLabel jLabel2NomeMotorista;
    private javax.swing.JLabel jLabel3TelefoneMotorista;
    private javax.swing.JLabel jLabel4CNHmotorista;
    private javax.swing.JLabel jLabel5VencimentoCNHmotorista;
    private javax.swing.JLabel jLabel5VencimentoCNHmotorista1;
    private javax.swing.JLabel jLabel6EnderecoMotorista;
    private javax.swing.JTextField jTextField1EnderecoMotorista;
    private javax.swing.JTextField jTextField1FotoURL;
    private javax.swing.JTextField jTextField1NomeMotorista;
    private javax.swing.JTextField jTextField1NumeroCNH;
    private javax.swing.JTextField jTextField1TelefoneMotorista;
    private javax.swing.JTextField jTextField1VencimentoCNH;
    // End of variables declaration//GEN-END:variables

}
