/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package telaVisao;

import com.nohair.controle.IMotoristaControle;
import com.nohair.controle.MotoristaControle;
import com.nohair.modelos.Motorista;
import com.nohair.persistencia.MotoristaDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class TelaAdminCadMotorista extends javax.swing.JFrame {
    IMotoristaControle MotoristaControle = new MotoristaControle();

    /** Creates new form TelaAdminCadMotorista */
    public TelaAdminCadMotorista() {
        initComponents();
        MotoristaDao objeto = new MotoristaDao();
        objeto.ChecarTxt();
        this.setLocationRelativeTo(null);
         try {
             ArrayList<Motorista> lista = MotoristaControle.listagem();
             if(!lista.isEmpty()){
                //imprimirDadosNaGrid(adminControle.listagem());
             }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
            
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2NomeMotorista = new javax.swing.JLabel();
        jLabel3TelefoneMotorista = new javax.swing.JLabel();
        jLabel4CNHmotorista = new javax.swing.JLabel();
        jLabel5VencimentoCNHmotorista = new javax.swing.JLabel();
        jLabel6EnderecoMotorista = new javax.swing.JLabel();
        jTextField1NomeMotorista = new javax.swing.JTextField();
        jTextField1TelefoneMotorista = new javax.swing.JTextField();
        jTextField1EnderecoMotorista = new javax.swing.JTextField();
        jTextField1NumeroCNH = new javax.swing.JTextField();
        jTextField1VencimentoCNH = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Motorista");

        jLabel2NomeMotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2NomeMotorista.setText("Nome");

        jLabel3TelefoneMotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3TelefoneMotorista.setText("Telefone");

        jLabel4CNHmotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4CNHmotorista.setText("Nº CNH");

        jLabel5VencimentoCNHmotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5VencimentoCNHmotorista.setText("Vencimento CNH");

        jLabel6EnderecoMotorista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6EnderecoMotorista.setText("Endereço");

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2NomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3TelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6EnderecoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4CNHmotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5VencimentoCNHmotorista)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1NomeMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(jTextField1TelefoneMotorista)
                                .addComponent(jTextField1EnderecoMotorista)
                                .addComponent(jTextField1NumeroCNH)
                                .addComponent(jTextField1VencimentoCNH))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2NomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1NomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3TelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1TelefoneMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6EnderecoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1EnderecoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4CNHmotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1NumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5VencimentoCNHmotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1VencimentoCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
           
            if(!jTextField1NomeMotorista.getText().equals("") && !jTextField1TelefoneMotorista.getText().equals("") && !jTextField1EnderecoMotorista.getText().equals("") && !jTextField1NumeroCNH.getText().equals("") && !jTextField1VencimentoCNH.getText().equals("")){
            
        
            Motorista objeto = new Motorista(0,jTextField1NomeMotorista.getText(),jTextField1TelefoneMotorista.getText(),jTextField1EnderecoMotorista.getText(),jTextField1NumeroCNH.getText(),jTextField1VencimentoCNH.getText());
            MotoristaControle.incluir(objeto);
            jTextField1NomeMotorista.setText("");
            jTextField1TelefoneMotorista.setText("");
            jTextField1EnderecoMotorista.setText("");
            jTextField1NumeroCNH.setText("");
            jTextField1VencimentoCNH.setText("");
            JOptionPane.showMessageDialog(this,"Motorista Cadastrado com sucesso");
            //imprimirDadosNaGrid(MotoristaControle.listagem());
            
            }                
            else{
                //Se houver campo vazio no cadastro e mostrado uma mensagem !
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar, confira se todos os dados foram inseridos corretamente ou contate o suporte pelo contato 62982971994");
            }    
            
          
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this,"Erro ao Cadastrar, contate o suporte pelo contato 62982971994");
           
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        telaAdminOpcoes f = new telaAdminOpcoes();
            this.dispose();                     // Fechar a tela ao abrir outra janela
            f.setLocationRelativeTo(null);      // Comando para centralizar a aplicação no centro do monitor
            f.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdminCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdminCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdminCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdminCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdminCadMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2NomeMotorista;
    private javax.swing.JLabel jLabel3TelefoneMotorista;
    private javax.swing.JLabel jLabel4CNHmotorista;
    private javax.swing.JLabel jLabel5VencimentoCNHmotorista;
    private javax.swing.JLabel jLabel6EnderecoMotorista;
    private javax.swing.JTextField jTextField1EnderecoMotorista;
    private javax.swing.JTextField jTextField1NomeMotorista;
    private javax.swing.JTextField jTextField1NumeroCNH;
    private javax.swing.JTextField jTextField1TelefoneMotorista;
    private javax.swing.JTextField jTextField1VencimentoCNH;
    // End of variables declaration//GEN-END:variables

}
